github-org-name: nyu-web-design
github-repo-name: course-materials
baseurl: /course-materials
title: Web Design & Computer Principles
description: >
  A fantastic voyage through web design and beginning front-end development
copyright: GNU General Public License, Version 3
layouts_dir: .jekyll/_layouts/
